In [5]:
import torch  
from torch import nn 
from torch.nn import functional as F 

## 一、读写Tensor

(1)单个张量

In [19]:
 x = torch.arange(4)  
torch.save(x, 'x-file')

In [21]:
x2 = torch.load('x-file',weights_only=True) 
x2

tensor([0, 1, 2, 3])

(2)张量列表

In [24]:
y = torch.zeros(4) 
torch.save([x, y],'x-files')  
x2, y2 = torch.load('x-files',weights_only=True)  
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

(3)从字符串映射到张量的字典

In [15]:
mydict = {'x': x, 'y': y} 
torch.save(mydict, 'mydict')  
mydict2 = torch.load('mydict',weights_only=True)  
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## 二、加载和保存模型参数

In [53]:
class MLP(nn.Module):  
    def __init__(self):  
        super().__init__()  
        self.hidden = nn.Linear(20, 256)  
        self.output = nn.Linear(256, 10)  
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))  
net = MLP()  
X = torch.randn(size=(2, 20))  
Y = net(X)
print(Y)

tensor([[-0.1398,  0.0443,  0.0252,  0.3792, -0.2074, -0.0826, -0.0323, -0.0907,
          0.2201,  0.0127],
        [ 0.1307,  0.0867, -0.3531, -0.5012, -0.2177,  0.2670, -0.0390, -0.2868,
          0.1411,  0.0864]], grad_fn=<AddmmBackward0>)


将模型的参数存储在一个叫做“mlp.params”的文件中。

In [56]:
torch.save(net.state_dict(), 'mlp.params')

In [58]:
clone = MLP()  
print(clone)
clone.load_state_dict(torch.load('mlp.params',weights_only=True))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)


MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [60]:
Y_clone = clone(X)  
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])